version: '3.8' 
services:
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   network_mode: host
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   healthcheck:
  #     test: ["CMD", "rabbitmqctl", "status"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: worker
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    network_mode: host
    privileged: true
    user: root
    volumes:
      - ./records:/app/records
      - ./.env:/app/.env
    environment:
      - RABBITMQ_HOST=localhost
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - RABBIT_MQ_QUEUE=call_queue
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1G

  pusher:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: pusher
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    network_mode: host
    privileged: true
    user: root
    volumes:
      - ./records:/app/records
      - ./.env:/app/.env
    environment:
      - RABBITMQ_HOST=localhost
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - RABBIT_MQ_QUEUE=call_queue
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

volumes:
  rabbitmq_data:
