apiVersion: v1
kind: PersistentVolume
metadata:
  name: records-pv-new
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/hoangphu7122002/callbot/records
